const baseTime = 1776312000000;

export const defaultProducts = [
  // --- NEW HARDWARE ADDITIONS ---
  {
    _id: 'new-1',
    id: 'new-1',
    name: 'NZXT Kraken X53 240mm AIO Liquid Cooler',
    slug: 'nzxt-kraken-x53-240mm-aio-liquid-cooler',
    category: 'CPU Accessories',
    brand: 'NZXT',
    priceCents: 999000,
    stock: 15,
    featured: true,
    description: 'NZXT KRAKEN X53 - 240MM AIO LIQUID COOLER (RL-KRX53-01). Features an RGB infinity mirror pump block, dual Aer P 120mm radiator fans, and CAM software integration.',
    images: ['https://res.cloudinary.com/d2zqpsu9/image/upload/v1790707046/yunax_products/kraken_x53_kjmojc.jpg'],
    highlights: ['240mm Radiator', 'Infinity Mirror RGB Pump', 'Aer P Radiator Fans', 'CAM Software Control'],
    specs: { brand: 'NZXT', model: 'RL-KRX53-01', radiatorSize: '240mm', fans: '2 x 120mm', socketSupport: 'Intel LGA 1700/1200 / AMD AM5/AM4' },
    createdAt: baseTime + 8000,
  },
  {
    _id: 'new-2',
    id: 'new-2',
    name: 'NZXT Kraken X63 280mm AIO Liquid Cooler',
    slug: 'nzxt-kraken-x63-280mm-aio-liquid-cooler',
    category: 'CPU Accessories',
    brand: 'NZXT',
    priceCents: 1090000,
    stock: 12,
    featured: true,
    description: 'NZXT KRAKEN X63 - 280MM AIO LIQUID COOLER (RL-KRX63-01). High-performance 280mm liquid cooler with re-rotatable RGB infinity mirror cap and dual Aer P 140mm fans.',
    images: ['https://res.cloudinary.com/d2zqpsu9/image/upload/v1790707047/yunax_products/kraken_x63_knxzdw.webp'],
    highlights: ['280mm Radiator', 'Rotatable RGB Infinity Mirror', 'Dual Aer P 140mm Fans', 'Reinforced Extended Tubing'],
    specs: { brand: 'NZXT', model: 'RL-KRX63-01', radiatorSize: '280mm', fans: '2 x 140mm', socketSupport: 'Intel LGA 1700/1200 / AMD AM5/AM4' },
    createdAt: baseTime + 7000,
  },
  {
    _id: 'new-3',
    id: 'new-3',
    name: 'NZXT H510 Compact Mid Tower Black/Black Chassis',
    slug: 'nzxt-h510-compact-mid-tower-chassis',
    category: 'Desktop',
    brand: 'NZXT',
    priceCents: 499900,
    stock: 20,
    featured: true,
    description: 'NZXT H510 COMPACT MID TOWER BLACK/BLACK CHASSIS (CA-H510B-B1). Sleek mid-tower case featuring flush tempered glass side panel, front USB-C, and cable management system.',
    images: ['https://res.cloudinary.com/d2zqpsu9/image/upload/v1790707048/yunax_products/nzxt_h510_tvzbwp.jpg'],
    highlights: ['Flush Tempered Glass Side Panel', 'USB 3.1 Gen 2 Front USB-C', 'Intuitive Cable Routing System', 'Removable Fan/Radiator Bracket'],
    specs: { brand: 'NZXT', model: 'CA-H510B-B1', type: 'Mid Tower', color: 'Matte Black/Black', sidePanel: 'Tempered Glass', motherboards: 'ATX, Micro-ATX, Mini-ITX' },
    createdAt: baseTime + 6000,
  },
  {
    _id: 'new-4',
    id: 'new-4',
    name: 'DeepCool Gammaxx L120 V2 Liquid Cooler (RGB)',
    slug: 'deepcool-gammaxx-l120-v2-liquid-cooler',
    category: 'CPU Accessories',
    brand: 'DeepCool',
    priceCents: 340000,
    stock: 25,
    description: 'DEEPCOOL LIQUID COOLER GAMMAXX L120 V2 (RGB LIGHTING) (DP-H12RF-GL120V2). Equipped with Anti-Leak Tech, 120mm RGB PWM fan, and 12V RGB pump illumination.',
    images: ['https://res.cloudinary.com/d2zqpsu9/image/upload/v1790707050/yunax_products/deepcool_l120_g55zez.jpg'],
    highlights: ['Anti-Leak Tech Inside', '120mm RGB PWM Fan', '12V RGB Pump Lighting', 'Ultra-large Copper CPU Block'],
    specs: { brand: 'DeepCool', model: 'DP-H12RF-GL120V2', radiatorSize: '120mm', fans: '1 x 120mm RGB', tech: 'Anti-Leak Technology' },
    createdAt: baseTime + 5000,
  },
  {
    _id: 'new-5',
    id: 'new-5',
    name: 'Antec Cooler A40 Pro CPU Cooler',
    slug: 'antec-a40-pro-cpu-cooler',
    category: 'CPU Accessories',
    brand: 'Antec',
    priceCents: 125000,
    stock: 30,
    description: 'ANTEC COOLER A40 PRO (0-761345-10923-9) CPU COOLER. Quiet air cooler with 4 direct-touch copper heatpipes, blue LED 92mm fan, and graphite heat sink fins.',
    images: ['https://res.cloudinary.com/d2zqpsu9/image/upload/v1790707051/yunax_products/antec_a40_llb8pa.jpg'],
    highlights: ['4 Direct-Touch Copper Heatpipes', '92mm Blue LED Fan', 'Graphite Thermal Coating', 'Universal Socket Mounting'],
    specs: { brand: 'Antec', model: '0-761345-10923-9', coolingType: 'Air Cooler', fanSize: '92mm Blue LED', heatpipes: '4 x Direct-Touch Copper' },
    createdAt: baseTime + 4000,
  },
  {
    _id: 'new-6',
    id: 'new-6',
    name: 'Cooler Master MasterLiquid ML360 Sub-Zero Liquid Cooler',
    slug: 'cooler-master-ml360-sub-zero-liquid-cooler',
    category: 'CPU Accessories',
    brand: 'Cooler Master',
    priceCents: 1990000,
    stock: 6,
    featured: true,
    description: 'COOLER MASTER ML360 SUB ZERO LIQUID COOLER (MLZ-D36M-A19PK-12IM016362). Sub-ambient thermoelectric (TEC) liquid cooler engineered with Intel Cryo Cooling Tech.',
    images: ['https://res.cloudinary.com/d2zqpsu9/image/upload/v1790707053/yunax_products/ml360_subzero_txt5v9.png'],
    highlights: ['Intel Cryo Cooling Technology', 'Sub-Ambient Thermoelectric Cooling', '360mm High-Density Radiator', 'Triple SF120R PWM Fans'],
    specs: { brand: 'Cooler Master', model: 'MLZ-D36M-A19PK-12IM016362', tech: 'Sub-Zero Thermoelectric (TEC)', radiatorSize: '360mm', fans: '3 x 120mm SF120R' },
    createdAt: baseTime + 3000,
  },
  {
    _id: 'new-7',
    id: 'new-7',
    name: 'Glorious GMMK Compact Mechanical Keyboard (Brown Switch)',
    slug: 'glorious-gmmk-compact-brown-switch',
    category: 'Gaming Accessories',
    brand: 'Glorious',
    priceCents: 770000,
    stock: 18,
    featured: true,
    description: 'GLORIOUS KEY BOARD GMMK-COMPACT-BRN. Modular 60% compact mechanical gaming keyboard with hot-swappable brown switches, RGB backlighting, and aluminum frame.',
    images: ['https://res.cloudinary.com/d2zqpsu9/image/upload/v1790707055/yunax_products/gmmk_compact_gpgbb4.jpg'],
    highlights: ['Hot-Swappable Modular Switches', '60% Ultra-Compact Layout', 'Pre-installed Gateron Brown Switches', 'Per-Key RGB Lighting'],
    specs: { brand: 'Glorious', model: 'GMMK-COMPACT-BRN', layout: '60% Compact (61 Key)', switchType: 'Tactile Brown', body: 'Sandblasted Aluminum' },
    createdAt: baseTime + 2000,
  },
  {
    _id: 'new-8',
    id: 'new-8',
    name: 'Glorious GMMK V2 Mechanical Keyboard (Brown Switch)',
    slug: 'glorious-gmmk-v2-brown-switch',
    category: 'Gaming Accessories',
    brand: 'Glorious',
    priceCents: 880000,
    stock: 14,
    featured: true,
    description: 'KEY BOARD GMMK-BRN-V2 GLORIOUS. Next-generation customizable mechanical gaming keyboard featuring CNC anodized top plate, hot-swappable PCB, and RGB lighting.',
    images: ['https://res.cloudinary.com/d2zqpsu9/image/upload/v1790707057/yunax_products/gmmk_v2_cyrxyi.jpg'],
    highlights: ['CNC Anodized Aluminum Top Frame', 'Hot-Swappable 5-Pin PCB', 'Pre-lubed Switches & Stabilizers', 'Per-Key RGB + Side Ambient Glow'],
    specs: { brand: 'Glorious', model: 'GMMK-BRN-V2', layout: 'Full / TKL Modular', switchType: 'Brown Tactile', illumination: 'Per-key RGB + Side Diffusers' },
    createdAt: baseTime + 1000,
  },
  // --- QUANTUM SERIES LAPTOPS ---
  {
    _id: 'default-1',
    id: 'default-1',
    name: 'Yunax Horizon 15 Air',
    slug: 'yunax-horizon-15-air',
    category: 'Laptops',
    brand: 'Yunax',
    priceCents: 6299000,
    stock: 12,
    featured: true,
    description: 'Ultra-slim 15.6-inch professional laptop designed for the modern nomad. Features a brushed magnesium chassis and military-grade durability.',
    images: ['https://res.cloudinary.com/d2zqpsu9/image/upload/v1790707058/yunax_products/w800_cfcsvu.png'],
    highlights: ['Intel Horizon-Core i7', 'Vivid-Glass Anti-glare', '16GB LPDDR5 / 1TB SSD', '180-degree Lay-flat hinge'],
    specs: { brand: 'Yunax', series: 'Horizon Air', processor: 'Pro-Stream i7 Gen 12', graphics: 'Iris Vision Graphics', memory: '16GB Dual-Channel', storage: '1TB Ultra-Fast SSD', battery: 'Fast charge 60% in 45m' },
    createdAt: baseTime,
  },
  {
    _id: 'default-2',
    id: 'default-2',
    name: 'Yunax Combat G15 Pro',
    slug: 'yunax-combat-g15-pro',
    category: 'Laptops',
    brand: 'Yunax',
    priceCents: 9499000,
    stock: 8,
    description: 'Battle-hardened gaming machine with high-altitude cooling and a reinforced tactical chassis. Built for extreme conditions.',
    images: ['https://res.cloudinary.com/d2zqpsu9/image/upload/v1790707059/yunax_products/w800_mthybw.png'],
    highlights: ['Combat-Spec Ryzen 7', 'Vision-RTX Graphics', '144Hz Tactical Display', 'Reinforced G-Chassis'],
    specs: { brand: 'Yunax', series: 'Combat G', model: 'G15-P', processor: 'Combat-7 7435HS', graphics: 'Vision-RTX 3050', memory: '16GB DDR5', storage: '1TB SSD', cooling: 'Dual-Fan Tactical System' },
    createdAt: baseTime - 1000,
  },
  {
    _id: 'default-3',
    id: 'default-3',
    name: 'Yunax StudioBook 15',
    slug: 'yunax-studiobook-15',
    category: 'Laptops',
    brand: 'Yunax',
    priceCents: 6799000,
    stock: 10,
    description: 'A masterpiece of design for creators. The StudioBook features a micro-edge color-accurate display and premium tactile keyboard.',
    images: ['https://res.cloudinary.com/d2zqpsu9/image/upload/v1790707030/yunax_products/filfkmawoq_atsrge.webp'],
    highlights: ['Creator-Grade Ryzen 5', 'Precision Color Display', 'Enhanced Creative Memory', '512GB Low-Latency Storage'],
    specs: { brand: 'Yunax', series: 'StudioBook', processor: 'Stream-Ready 4500U', graphics: 'Studio-Integrated Graphics', memory: '16GB High-Speed', storage: '512GB Ultra-NVMe', weight: '1.68 kg' },
    createdAt: baseTime - 2000,
  },
  {
    _id: 'default-4',
    id: 'default-4',
    name: 'Yunax Predator V Gaming',
    slug: 'yunax-predator-v-gaming',
    category: 'Laptops',
    brand: 'Yunax',
    priceCents: 8999000,
    stock: 6,
    featured: true,
    description: 'Elite gaming performance in a minimalist frame. Features the Omen-inspired thermal array for sustained peak performance.',
    images: ['https://res.cloudinary.com/d2zqpsu9/image/upload/v1790707032/yunax_products/Hero_20Image_201_mhzvsx.png'],
    highlights: ['Intel Ultra-5 Processor', 'Phantom-RTX 4050', 'High-Refresh Panel', 'Advanced Thermal Logic'],
    specs: { brand: 'Yunax', series: 'Predator V', processor: 'Pro-Stream i5', graphics: 'Vision-RTX 4050', memory: '16GB DDR4', storage: '1TB NVMe', cooling: 'Omen-Legacy Dual-Fan' },
    createdAt: baseTime - 3000,
  },

  // --- ELITE PERIPHERALS ---
  {
    _id: 'default-5',
    id: 'default-5',
    name: 'Yunax Tactile Pro TKL',
    slug: 'yunax-tactile-pro-keyboard',
    category: 'Gaming Accessories',
    brand: 'Yunax',
    priceCents: 1899000,
    stock: 15,
    description: 'Precision mechanical engineering with proprietary magnetic switches. Zero latency for elite competitive play.',
    images: ['https://res.cloudinary.com/d2zqpsu9/image/upload/v1790707036/yunax_products/keyboard_apex_u7lt1r.jpg'],
    highlights: ['Yunax Magnetic Switches', 'Integrated Status OLED', 'Aeronautical Aluminum', 'Precision PBT keycaps'],
    specs: { switches: 'Yunax Omni-Magnetic', response: '0.1ms', actuation: 'Variable 0.2mm - 4.0mm', lighting: 'Aura-RGB Per-Key', software: 'Yunax Control Center' },
    createdAt: baseTime - 4000,
  },
  {
    _id: 'default-6',
    id: 'default-6',
    name: 'Yunax Swift-Wing Wireless',
    slug: 'yunax-swift-wing-mouse',
    category: 'Gaming Accessories',
    brand: 'Yunax',
    priceCents: 1299000,
    stock: 20,
    featured: true,
    description: 'The lightest competitive mouse in the Yunax lineup. Engineered for speed and surgical accuracy.',
    images: ['https://res.cloudinary.com/d2zqpsu9/image/upload/v1790707039/yunax_products/mouse_viper_l94z0v.jpg'],
    highlights: ['30K Precision Sensor', 'Extremely Low 70g Weight', 'Infinite-Life Optical Clicks', 'Swift-Link Wireless Tech'],
    specs: { weight: '70g', sensor: 'Precision-30K', battery: '100+ Hours', buttons: '8 Fully Custom', acceleration: '50G Max' },
    createdAt: baseTime - 5000,
  },
  {
    _id: 'default-7',
    id: 'default-7',
    name: 'Yunax Nebula 7.1 Headset',
    slug: 'yunax-nebula-rgb-headset',
    category: 'Gaming Accessories',
    brand: 'Yunax',
    priceCents: 549000,
    stock: 35,
    description: 'Immersive spatial audio experience with memory foam comfort for extended operations.',
    images: ['https://res.cloudinary.com/d2zqpsu9/image/upload/v1790707064/yunax_products/gadgets_c9krq7.jpg'],
    highlights: ['7.1 Spatial Audio', 'Crystal-Clear Mic', 'Aura-RGB Accents', 'Pro-Grade Build'],
    specs: { drivers: '53mm Precision', mics: 'Noise-Isolated', weight: '310g', cable: '2.5m Reinforeced', connectivity: 'Dual-Mode' },
    createdAt: baseTime - 6000,
  },
  {
    _id: 'default-8',
    id: 'default-8',
    name: 'Yunax Command Pro Chair',
    slug: 'yunax-command-pro-chair',
    category: 'Gaming Accessories',
    brand: 'Yunax',
    priceCents: 2490000,
    stock: 5,
    description: 'The ultimate throne for your gaming rig. Features full ergonomic control and magnetic accessory support.',
    images: ['https://res.cloudinary.com/d2zqpsu9/image/upload/v1790707065/yunax_products/gamiinglaptopandassecroies_z3kx43.jpg'],
    highlights: ['4D Tactile Armrests', 'Magnetic Lumbar System', 'Full Recline Support', 'Elite PU Leather'],
    specs: { material: 'Proprietary PU', base: 'Industrial Grade', capacity: '130kg', frame: 'Full-Steel Armor', warranty: '5 Year Frame' },
    createdAt: baseTime - 7000,
  },

  // --- ACCESSORY ECOSYSTEM ---
  {
    _id: 'default-9',
    id: 'default-9',
    name: 'Yunax Nexus 10-in-1 Hub',
    slug: 'yunax-nexus-hub',
    category: 'Laptop Accessories',
    brand: 'Yunax',
    priceCents: 749000,
    stock: 40,
    description: 'Expanding your horizons with a single connection. The Nexus hub provides a full workstation array in a compact shell.',
    images: ['https://res.cloudinary.com/d2zqpsu9/image/upload/v1790707071/yunax_products/hub_hyperdrive_ghwkch.jpg'],
    highlights: ['4K Crystal Display Out', 'Elite Power Delivery', 'High-Speed Card Array', 'Full GbE Link'],
    specs: { ports: '10 Master Ports', material: 'Industrial Aluminum', output: '4K @ 60Hz', power: '100W Dynamic', link: 'USB-C Elite' },
    createdAt: baseTime - 8000,
  },
  {
    _id: 'default-10',
    id: 'default-10',
    name: 'Yunax Chill-Stream Pad',
    slug: 'yunax-chill-stream',
    category: 'Laptop Accessories',
    brand: 'Yunax',
    priceCents: 229000,
    stock: 50,
    description: 'Combat thermal fatigue with high-pressure airflow. Silent fans integrated into a premium mesh frame.',
    images: ['https://res.cloudinary.com/d2zqpsu9/image/upload/v1790707065/yunax_products/gamiinglaptopandassecroies_z3kx43.jpg'],
    highlights: ['Triple High-Flow Fans', 'Industrial Mesh Top', 'Variable Angle Base', 'Silent Profile'],
    specs: { fans: '3 x 120mm Elite', dba: 'Low 18dB', steps: '5 Level Angle', power: 'Bus Powered', lighting: 'Deep Blue Aura' },
    createdAt: baseTime - 9000,
  },
  {
    _id: 'default-11',
    id: 'default-11',
    name: 'Yunax Armor-Carbon Sleeve',
    slug: 'yunax-armor-sleeve',
    category: 'Laptop Accessories',
    brand: 'Yunax',
    priceCents: 149000,
    stock: 30,
    description: 'Rugged protection with a sleek aesthetic. Shock-absorbent frame wrapped in weather-proof carbon textile.',
    images: ['https://res.cloudinary.com/d2zqpsu9/image/upload/v1790707067/yunax_products/mobileassceories_cm6ozu.jpg'],
    highlights: ['Weather-Proofweave', 'Impact-Resistant Core', 'Quick-Access Bay', 'Low-Profile Design'],
    specs: { material: 'Carbon Shield EVA', size: '14" - 16" Universal', weight: '260g', seal: 'Aqua-Guard Zipper' },
    createdAt: baseTime - 10000,
  },

  // --- PRECISION COMPONENTS ---
  {
    _id: 'default-12',
    id: 'default-12',
    name: 'Yunax Cryo-Max 360 LCD',
    slug: 'yunax-cryo-max-cooler',
    category: 'CPU Accessories',
    brand: 'Yunax',
    priceCents: 2499000,
    stock: 8,
    featured: true,
    description: 'Extreme thermal management with an integrated system monitor. Customizable display for real-time diagnostics.',
    images: ['https://res.cloudinary.com/d2zqpsu9/image/upload/v1790707042/yunax_products/cooler_kraken_zykh3z.jpg'],
    highlights: ['High-Def Monitoring LCD', '360mm Heat Exchanger', 'Silent-Flow Pump', 'Vortex RGB Fans'],
    specs: { pump: '9th Gen Flow-Control', display: 'High-Contrast OLED', fans: '3 x Vortex-120', compatibility: 'All Modern Sockets', warranty: '6 Year Limited' },
    createdAt: baseTime - 11000,
  },
  {
    _id: 'default-13',
    id: 'default-13',
    name: 'Yunax Vortex Fan Pack',
    slug: 'yunax-vortex-fans',
    category: 'CPU Accessories',
    brand: 'Yunax',
    priceCents: 399000,
    stock: 60,
    description: 'High-static pressure fans with mesmerizing circular lighting. The lungs of your gaming PC.',
    images: ['https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&q=80&w=800'],
    highlights: ['Infinite Mirror Tech', 'Precision Hydro-Bearing', 'Aura-Sync Ready', '3-Fan Master Pack'],
    specs: { rpm: 'Master-1800', flow: '60 CFM', noise: 'Surgical Silent', link: 'PWM Digital', control: 'Master Hub Inc.' },
    createdAt: baseTime - 12000,
  },

  // --- DESKTOP STATIONS ---
  {
    _id: 'default-14',
    id: 'default-14',
    name: 'Yunax Zenith Pro One',
    slug: 'yunax-zenith-pro-desktop',
    category: 'CPU Accessories',
    brand: 'Yunax',
    priceCents: 44999000,
    stock: 3,
    featured: true,
    description: 'Our most powerful build ever. Hand-assembled with the industry\'s best components for zero bottlenecks.',
    images: ['https://res.cloudinary.com/d2zqpsu9/image/upload/v1790707044/yunax_products/desktop_zenith_edi2lm.jpg'],
    highlights: ['Elite Ultra-9 14th Gen', 'Phantom-RTX 4090 24GB', '64GB Infinity RAM', 'Liquid-State Cooling'],
    specs: { cpu: 'Core Ultra 9', gpu: 'Elite RTX 4090', ram: '64GB 6000MHz', psu: '1200W Titanium', case: 'Glass-Wing Pro' },
    createdAt: baseTime - 13000,
  },
  {
    _id: 'default-15',
    id: 'default-15',
    name: 'Yunax Studio Mini-PC',
    slug: 'yunax-studio-mini',
    category: 'Desktop',
    brand: 'Yunax',
    priceCents: 7490000,
    stock: 12,
    description: 'Pro performance in an ultra-compact chassis. Perfect for designers and high-end office setups.',
    images: ['https://res.cloudinary.com/d2zqpsu9/image/upload/v1790707063/yunax_products/editingsystem_ssnkf1.jpg'],
    highlights: ['Elite Quad-Core i7', '32GB Compact RAM', '2TB SSD Link', 'Multi-Monitor Ready'],
    specs: { form: 'Micro-Elite', cpu: 'Core i7 Studio', graphics: 'Cloud-Ready Vision', link: 'Thunderbolt Quad', mount: 'Pro-VESA' },
    createdAt: baseTime - 14000,
  },

  // --- WORKSPACE ACCESSORIES ---
  {
    _id: 'default-16',
    id: 'default-16',
    name: 'Yunax Infinity G9 Ultra',
    slug: 'yunax-infinity-g9-monitor',
    category: 'Desktop Accessories',
    brand: 'Yunax',
    priceCents: 12499000,
    stock: 7,
    description: 'A window into another world. The 49-inch Infinity G9 offers the most immersive panoramic experience available.',
    images: ['https://res.cloudinary.com/d2zqpsu9/image/upload/v1790707073/yunax_products/monitor_odyssey_stsiyj.jpg'],
    highlights: ['49" Curved Ultra-Wide', 'Quantum Matrix Display', '240Hz Response System', 'Elite-Dynamic HDR 2000'],
    specs: { resolution: '5120 x 1440', curvature: '1000R Elite', refresh: '240Hz', ports: 'Triple-Link HDMI/DP', technology: 'Quantum Matrix Mini-LED' },
    createdAt: baseTime - 15000,
  },
  {
    _id: 'default-17',
    id: 'default-17',
    name: 'Yunax Clarity-Studio Mic',
    slug: 'yunax-clarity-mic',
    category: 'Desktop Accessories',
    brand: 'Yunax',
    priceCents: 1290000,
    stock: 15,
    description: 'Professional grade capture for your voice. Features a high-fidelity capsule and built-in noise isolation.',
    images: ['https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&q=80&w=800'],
    highlights: ['Studio Master Capsule', 'Zero-Latency Feed', 'Integrated Pop Shield', 'Pro Digital Link'],
    specs: { pattern: 'Studio Cardioid', range: '20Hz - 22kHz', depth: '32-bit Elite', rate: '192kHz', body: 'Reinforced Alloy' },
    createdAt: baseTime - 16000,
  },
  {
    _id: 'default-18',
    id: 'default-18',
    name: 'Yunax Vision-Pro 4K Cam',
    slug: 'yunax-vision-pro-cam',
    category: 'Desktop Accessories',
    brand: 'Yunax',
    priceCents: 849000,
    stock: 22,
    description: 'Hyper-clear 4K visual stream for professional presence. AI-driven focus and lighting adjustment.',
    images: ['https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&q=80&w=800'],
    highlights: ['True 4K Digital Feed', 'AI Intelligent Tracking', 'HDR Contrast Balance', 'Crystal Audio Arrays'],
    specs: { res: 'Ultra-HD 4K', angle: '95-degree Pro', privacy: 'Physical Armor', mic: 'Dual Stereo Beam', mount: 'Precision Clamp' },
    createdAt: baseTime - 17000,
  },
  {
    _id: 'default-19',
    id: 'default-19',
    name: 'Yunax Acoustic Pro One',
    slug: 'yunax-acoustic-pro-speakers',
    category: 'Desktop Accessories',
    brand: 'Yunax',
    priceCents: 1890000,
    stock: 10,
    description: 'Audiophile grade desktop audio. Features carbon fiber drivers and a premium hand-finished cabinet.',
    images: ['https://images.unsplash.com/photo-1623150531061-00109968832a?auto=format&fit=crop&q=80&w=800'],
    highlights: ['Carbon Fiber Drivers', 'High-Fidelity Bluetooth', 'Hand-Crafted Cabinets', 'Master Tuning'],
    specs: { power: '80W Peak Elite', tweeters: 'Silk-Dome', woofers: 'Carbon Matrix', link: 'Wireless / Optical', finish: 'Elite Walnut' },
    createdAt: baseTime - 18000,
  },
];

export const getDefaultProducts = () => defaultProducts.map((p) => ({
  ...p,
  images: [...(p.images || [])],
  highlights: [...(p.highlights || [])],
  specs: { ...(p.specs || {}) },
}));

export const findDefaultProductBySlug = (slug) =>
  getDefaultProducts().find((p) => p.slug === slug) || null;
