const baseTime = 1776312000000;

export const defaultProducts = [
  // --- QUANTUM SERIES LAPTOPS ---
  {
    _id: 'default-1',
    id: 'default-1',
    name: 'Yunax Horizon 15 Air',
    slug: 'yunax-horizon-15-air',
    category: 'Laptops',
    brand: 'Yunax',
    priceCents: 6299000,
    stock: 12,
    featured: true,
    description: 'Ultra-slim 15.6-inch professional laptop designed for the modern nomad. Features a brushed magnesium chassis and military-grade durability.',
    images: ['https://dlcdnwebimgs.asus.com/gain/ac75b6f3-379c-4507-b027-2a962cf9c9e7/w800'],
    highlights: ['Intel Horizon-Core i7', 'Vivid-Glass Anti-glare', '16GB LPDDR5 / 1TB SSD', '180-degree Lay-flat hinge'],
    specs: { brand: 'Yunax', series: 'Horizon Air', processor: 'Pro-Stream i7 Gen 12', graphics: 'Iris Vision Graphics', memory: '16GB Dual-Channel', storage: '1TB Ultra-Fast SSD', battery: 'Fast charge 60% in 45m' },
    createdAt: baseTime,
  },
  {
    _id: 'default-2',
    id: 'default-2',
    name: 'Yunax Combat G15 Pro',
    slug: 'yunax-combat-g15-pro',
    category: 'Laptops',
    brand: 'Yunax',
    priceCents: 9499000,
    stock: 8,
    description: 'Battle-hardened gaming machine with high-altitude cooling and a reinforced tactical chassis. Built for extreme conditions.',
    images: ['https://dlcdnwebimgs.asus.com/gain/3166c96d-5c61-4ae7-9d62-d272df1fe385/w800'],
    highlights: ['Combat-Spec Ryzen 7', 'Vision-RTX Graphics', '144Hz Tactical Display', 'Reinforced G-Chassis'],
    specs: { brand: 'Yunax', series: 'Combat G', model: 'G15-P', processor: 'Combat-7 7435HS', graphics: 'Vision-RTX 3050', memory: '16GB DDR5', storage: '1TB SSD', cooling: 'Dual-Fan Tactical System' },
    createdAt: baseTime - 1000,
  },
  {
    _id: 'default-3',
    id: 'default-3',
    name: 'Yunax StudioBook 15',
    slug: 'yunax-studiobook-15',
    category: 'Laptops',
    brand: 'Yunax',
    priceCents: 6799000,
    stock: 10,
    description: 'A masterpiece of design for creators. The StudioBook features a micro-edge color-accurate display and premium tactile keyboard.',
    images: ['https://hp.widen.net/content/filfkmawoq/webp/filfkmawoq.png?color=ffffff00&dpi=72&h=860&w=1146'],
    highlights: ['Creator-Grade Ryzen 5', 'Precision Color Display', 'Enhanced Creative Memory', '512GB Low-Latency Storage'],
    specs: { brand: 'Yunax', series: 'StudioBook', processor: 'Stream-Ready 4500U', graphics: 'Studio-Integrated Graphics', memory: '16GB High-Speed', storage: '512GB Ultra-NVMe', weight: '1.68 kg' },
    createdAt: baseTime - 2000,
  },
  {
    _id: 'default-4',
    id: 'default-4',
    name: 'Yunax Predator V Gaming',
    slug: 'yunax-predator-v-gaming',
    category: 'Laptops',
    brand: 'Yunax',
    priceCents: 8999000,
    stock: 6,
    featured: true,
    description: 'Elite gaming performance in a minimalist frame. Features the Omen-inspired thermal array for sustained peak performance.',
    images: ['https://www.hp.com/content/dam/sites/omen/worldwide/laptops/2022-victus-15-intel/Hero%20Image%201.png'],
    highlights: ['Intel Ultra-5 Processor', 'Phantom-RTX 4050', 'High-Refresh Panel', 'Advanced Thermal Logic'],
    specs: { brand: 'Yunax', series: 'Predator V', processor: 'Pro-Stream i5', graphics: 'Vision-RTX 4050', memory: '16GB DDR4', storage: '1TB NVMe', cooling: 'Omen-Legacy Dual-Fan' },
    createdAt: baseTime - 3000,
  },

  // --- ELITE PERIPHERALS ---
  {
    _id: 'default-5',
    id: 'default-5',
    name: 'Yunax Tactile Pro TKL',
    slug: 'yunax-tactile-pro-keyboard',
    category: 'Gaming Accessories',
    brand: 'Yunax',
    priceCents: 1899000,
    stock: 15,
    description: 'Precision mechanical engineering with proprietary magnetic switches. Zero latency for elite competitive play.',
    images: ['/products/new/keyboard_apex.png'],
    highlights: ['Yunax Magnetic Switches', 'Integrated Status OLED', 'Aeronautical Aluminum', 'Precision PBT keycaps'],
    specs: { switches: 'Yunax Omni-Magnetic', response: '0.1ms', actuation: 'Variable 0.2mm - 4.0mm', lighting: 'Aura-RGB Per-Key', software: 'Yunax Control Center' },
    createdAt: baseTime - 4000,
  },
  {
    _id: 'default-6',
    id: 'default-6',
    name: 'Yunax Swift-Wing Wireless',
    slug: 'yunax-swift-wing-mouse',
    category: 'Gaming Accessories',
    brand: 'Yunax',
    priceCents: 1299000,
    stock: 20,
    featured: true,
    description: 'The lightest competitive mouse in the Yunax lineup. Engineered for speed and surgical accuracy.',
    images: ['/products/new/mouse_viper.png'],
    highlights: ['30K Precision Sensor', 'Extremely Low 70g Weight', 'Infinite-Life Optical Clicks', 'Swift-Link Wireless Tech'],
    specs: { weight: '70g', sensor: 'Precision-30K', battery: '100+ Hours', buttons: '8 Fully Custom', acceleration: '50G Max' },
    createdAt: baseTime - 5000,
  },
  {
    _id: 'default-7',
    id: 'default-7',
    name: 'Yunax Nebula 7.1 Headset',
    slug: 'yunax-nebula-rgb-headset',
    category: 'Gaming Accessories',
    brand: 'Yunax',
    priceCents: 549000,
    stock: 35,
    description: 'Immersive spatial audio experience with memory foam comfort for extended operations.',
    images: ['/products/gadgets.jpeg'],
    highlights: ['7.1 Spatial Audio', 'Crystal-Clear Mic', 'Aura-RGB Accents', 'Pro-Grade Build'],
    specs: { drivers: '53mm Precision', mics: 'Noise-Isolated', weight: '310g', cable: '2.5m Reinforeced', connectivity: 'Dual-Mode' },
    createdAt: baseTime - 6000,
  },
  {
    _id: 'default-8',
    id: 'default-8',
    name: 'Yunax Command Pro Chair',
    slug: 'yunax-command-pro-chair',
    category: 'Gaming Accessories',
    brand: 'Yunax',
    priceCents: 2490000,
    stock: 5,
    description: 'The ultimate throne for your gaming rig. Features full ergonomic control and magnetic accessory support.',
    images: ['/products/gamiinglaptopandassecroies.jpeg'],
    highlights: ['4D Tactile Armrests', 'Magnetic Lumbar System', 'Full Recline Support', 'Elite PU Leather'],
    specs: { material: 'Proprietary PU', base: 'Industrial Grade', capacity: '130kg', frame: 'Full-Steel Armor', warranty: '5 Year Frame' },
    createdAt: baseTime - 7000,
  },

  // --- ACCESSORY ECOSYSTEM ---
  {
    _id: 'default-9',
    id: 'default-9',
    name: 'Yunax Nexus 10-in-1 Hub',
    slug: 'yunax-nexus-hub',
    category: 'Laptop Accessories',
    brand: 'Yunax',
    priceCents: 749000,
    stock: 40,
    description: 'Expanding your horizons with a single connection. The Nexus hub provides a full workstation array in a compact shell.',
    images: ['/products/new/hub_hyperdrive.png'],
    highlights: ['4K Crystal Display Out', 'Elite Power Delivery', 'High-Speed Card Array', 'Full GbE Link'],
    specs: { ports: '10 Master Ports', material: 'Industrial Aluminum', output: '4K @ 60Hz', power: '100W Dynamic', link: 'USB-C Elite' },
    createdAt: baseTime - 8000,
  },
  {
    _id: 'default-10',
    id: 'default-10',
    name: 'Yunax Chill-Stream Pad',
    slug: 'yunax-chill-stream',
    category: 'Laptop Accessories',
    brand: 'Yunax',
    priceCents: 229000,
    stock: 50,
    description: 'Combat thermal fatigue with high-pressure airflow. Silent fans integrated into a premium mesh frame.',
    images: ['/products/gamiinglaptopandassecroies.jpeg'],
    highlights: ['Triple High-Flow Fans', 'Industrial Mesh Top', 'Variable Angle Base', 'Silent Profile'],
    specs: { fans: '3 x 120mm Elite', dba: 'Low 18dB', steps: '5 Level Angle', power: 'Bus Powered', lighting: 'Deep Blue Aura' },
    createdAt: baseTime - 9000,
  },
  {
    _id: 'default-11',
    id: 'default-11',
    name: 'Yunax Armor-Carbon Sleeve',
    slug: 'yunax-armor-sleeve',
    category: 'Laptop Accessories',
    brand: 'Yunax',
    priceCents: 149000,
    stock: 30,
    description: 'Rugged protection with a sleek aesthetic. Shock-absorbent frame wrapped in weather-proof carbon textile.',
    images: ['/products/mobileassceories.jpeg'],
    highlights: ['Weather-Proofweave', 'Impact-Resistant Core', 'Quick-Access Bay', 'Low-Profile Design'],
    specs: { material: 'Carbon Shield EVA', size: '14" - 16" Universal', weight: '260g', seal: 'Aqua-Guard Zipper' },
    createdAt: baseTime - 10000,
  },

  // --- PRECISION COMPONENTS ---
  {
    _id: 'default-12',
    id: 'default-12',
    name: 'Yunax Cryo-Max 360 LCD',
    slug: 'yunax-cryo-max-cooler',
    category: 'CPU Accessories',
    brand: 'Yunax',
    priceCents: 2499000,
    stock: 8,
    featured: true,
    description: 'Extreme thermal management with an integrated system monitor. Customizable display for real-time diagnostics.',
    images: ['/products/new/cooler_kraken.png'],
    highlights: ['High-Def Monitoring LCD', '360mm Heat Exchanger', 'Silent-Flow Pump', 'Vortex RGB Fans'],
    specs: { pump: '9th Gen Flow-Control', display: 'High-Contrast OLED', fans: '3 x Vortex-120', compatibility: 'All Modern Sockets', warranty: '6 Year Limited' },
    createdAt: baseTime - 11000,
  },
  {
    _id: 'default-13',
    id: 'default-13',
    name: 'Yunax Vortex Fan Pack',
    slug: 'yunax-vortex-fans',
    category: 'CPU Accessories',
    brand: 'Yunax',
    priceCents: 399000,
    stock: 60,
    description: 'High-static pressure fans with mesmerizing circular lighting. The lungs of your gaming PC.',
    images: ['https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&q=80&w=800'],
    highlights: ['Infinite Mirror Tech', 'Precision Hydro-Bearing', 'Aura-Sync Ready', '3-Fan Master Pack'],
    specs: { rpm: 'Master-1800', flow: '60 CFM', noise: 'Surgical Silent', link: 'PWM Digital', control: 'Master Hub Inc.' },
    createdAt: baseTime - 12000,
  },

  // --- DESKTOP STATIONS ---
  {
    _id: 'default-14',
    id: 'default-14',
    name: 'Yunax Zenith Pro One',
    slug: 'yunax-zenith-pro-desktop',
    category: 'CPU Accessories',
    brand: 'Yunax',
    priceCents: 44999000,
    stock: 3,
    featured: true,
    description: 'Our most powerful build ever. Hand-assembled with the industry\'s best components for zero bottlenecks.',
    images: ['/products/new/desktop_zenith.png'],
    highlights: ['Elite Ultra-9 14th Gen', 'Phantom-RTX 4090 24GB', '64GB Infinity RAM', 'Liquid-State Cooling'],
    specs: { cpu: 'Core Ultra 9', gpu: 'Elite RTX 4090', ram: '64GB 6000MHz', psu: '1200W Titanium', case: 'Glass-Wing Pro' },
    createdAt: baseTime - 13000,
  },
  {
    _id: 'default-15',
    id: 'default-15',
    name: 'Yunax Studio Mini-PC',
    slug: 'yunax-studio-mini',
    category: 'Desktop',
    brand: 'Yunax',
    priceCents: 7490000,
    stock: 12,
    description: 'Pro performance in an ultra-compact chassis. Perfect for designers and high-end office setups.',
    images: ['/products/editingsystem.jpeg'],
    highlights: ['Elite Quad-Core i7', '32GB Compact RAM', '2TB SSD Link', 'Multi-Monitor Ready'],
    specs: { form: 'Micro-Elite', cpu: 'Core i7 Studio', graphics: 'Cloud-Ready Vision', link: 'Thunderbolt Quad', mount: 'Pro-VESA' },
    createdAt: baseTime - 14000,
  },

  // --- WORKSPACE ACCESSORIES ---
  {
    _id: 'default-16',
    id: 'default-16',
    name: 'Yunax Infinity G9 Ultra',
    slug: 'yunax-infinity-g9-monitor',
    category: 'Desktop Accessories',
    brand: 'Yunax',
    priceCents: 12499000,
    stock: 7,
    description: 'A window into another world. The 49-inch Infinity G9 offers the most immersive panoramic experience available.',
    images: ['/products/new/monitor_odyssey.png'],
    highlights: ['49" Curved Ultra-Wide', 'Quantum Matrix Display', '240Hz Response System', 'Elite-Dynamic HDR 2000'],
    specs: { resolution: '5120 x 1440', curvature: '1000R Elite', refresh: '240Hz', ports: 'Triple-Link HDMI/DP', technology: 'Quantum Matrix Mini-LED' },
    createdAt: baseTime - 15000,
  },
  {
    _id: 'default-17',
    id: 'default-17',
    name: 'Yunax Clarity-Studio Mic',
    slug: 'yunax-clarity-mic',
    category: 'Desktop Accessories',
    brand: 'Yunax',
    priceCents: 1290000,
    stock: 15,
    description: 'Professional grade capture for your voice. Features a high-fidelity capsule and built-in noise isolation.',
    images: ['https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&q=80&w=800'],
    highlights: ['Studio Master Capsule', 'Zero-Latency Feed', 'Integrated Pop Shield', 'Pro Digital Link'],
    specs: { pattern: 'Studio Cardioid', range: '20Hz - 22kHz', depth: '32-bit Elite', rate: '192kHz', body: 'Reinforced Alloy' },
    createdAt: baseTime - 16000,
  },
  {
    _id: 'default-18',
    id: 'default-18',
    name: 'Yunax Vision-Pro 4K Cam',
    slug: 'yunax-vision-pro-cam',
    category: 'Desktop Accessories',
    brand: 'Yunax',
    priceCents: 849000,
    stock: 22,
    description: 'Hyper-clear 4K visual stream for professional presence. AI-driven focus and lighting adjustment.',
    images: ['https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&q=80&w=800'],
    highlights: ['True 4K Digital Feed', 'AI Intelligent Tracking', 'HDR Contrast Balance', 'Crystal Audio Arrays'],
    specs: { res: 'Ultra-HD 4K', angle: '95-degree Pro', privacy: 'Physical Armor', mic: 'Dual Stereo Beam', mount: 'Precision Clamp' },
    createdAt: baseTime - 17000,
  },
  {
    _id: 'default-19',
    id: 'default-19',
    name: 'Yunax Acoustic Pro One',
    slug: 'yunax-acoustic-pro-speakers',
    category: 'Desktop Accessories',
    brand: 'Yunax',
    priceCents: 1890000,
    stock: 10,
    description: 'Audiophile grade desktop audio. Features carbon fiber drivers and a premium hand-finished cabinet.',
    images: ['https://images.unsplash.com/photo-1623150531061-00109968832a?auto=format&fit=crop&q=80&w=800'],
    highlights: ['Carbon Fiber Drivers', 'High-Fidelity Bluetooth', 'Hand-Crafted Cabinets', 'Master Tuning'],
    specs: { power: '80W Peak Elite', tweeters: 'Silk-Dome', woofers: 'Carbon Matrix', link: 'Wireless / Optical', finish: 'Elite Walnut' },
    createdAt: baseTime - 18000,
  },
];

export const getDefaultProducts = () => defaultProducts.map((p) => ({
  ...p,
  images: [...(p.images || [])],
  highlights: [...(p.highlights || [])],
  specs: { ...(p.specs || {}) },
}));

export const findDefaultProductBySlug = (slug) =>
  getDefaultProducts().find((p) => p.slug === slug) || null;
